### PR TITLE
A few tweaks to panel cropping.

### PR DESCRIPTION
**Pull request by codeviking**
- Aggressively crop with a small hard-coded value for handling ascenders / descenders.
- Always set the height to the panel height, don't worry about aspect ratio (it _should_ be maintained by panel dimensions).
- Apply mechanism for determining the top to the two-column layout as well as the top + two column layout.

@aria42

### CODE REVIEW

**Comment by codeviking** [comment]
I hacked on one more commit, it's a little rough but it returns the section's y offset with `jumpToSection` -- I use this to show an indicator in the UI after jumping to a section.

We can standardize / clean this up later (or LMK if you want me to clean it up now).

**Comment by codeviking** [comment]
Bump @aria42 (though no hurry as we're currently simply pointed at this branch).

**Comment by codeviking** [comment]
Ping @aria42 -- Once this is merged I think I'll publish a version to `npm` and peg scholar at that release (removing the submodule).   Let me know if that sounds good to you too.

**Comment by aria42** [comment]
Merging.

**Pull request merged**
